### PR TITLE
WIP: add visualizer test

### PR DESCRIPTION
**Pull request by SenWu**

### CODE REVIEW

**Comment by HiromuHota** [comment]
Seems like `apt install ghostscript` is the missing piece.
See https://travis-ci.com/HiromuHota/fonduer/jobs/197987440

**Comment by SenWu** [comment]
Super! Can you update this PR? or make another PR here? Thanks!!!

**Comment by HiromuHota** [comment]
Sure thing.

**Comment by HiromuHota** [comment]
I submitted a new PR #255 for this.

**Pull request closed without merging**
