### PR TITLE
Update setup-miniconda to avoid the use of add-path and set-env

### PR DESCRIPTION
**Pull request by HiromuHota**
## Description of the problems or issues
goanpeca/setup-miniconda@v1 is outdated and failed #530.

**Is your pull request related to a problem? Please describe.**
#530 failed.

**Does your pull request fix any issue.**
#530

## Description of the proposed changes
Update goanpeca/setup-miniconda to avoid the use of add-path and set-env.

## Test plan
All existing tests should pass.

## Checklist

* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.
* [ ] I have updated the CHANGELOG.rst accordingly.

### CODE REVIEW

**Comment by HiromuHota** [comment]
Tests are still failing.
Now:
spacy-2.3.5
en_core_web_sm==2.3.1

The last successful build (https://github.com/HazyResearch/fonduer/runs/1311404187?check_suite_focus=true):
spacy-2.3.2
en_core_web_sm==2.3.1

**Comment by HiromuHota** [comment]
spacy==2.3.3 is not compatible with our tests.

**Comment by HiromuHota** [comment]
Looks like spacy sentencizes at different places between 2.3.2 and 2.3.3.

The original document:

```
0,b373d4199a2e1d24574cf307edd4687fd2a0cd7a7e1e94f7c2ff0419803be8d6,1,"['spine/degenerative', 'scoliosis']",2,/lfs/raiders2/0/jdunnmon/repos/metal-experiments/data/openi/raw_reports/2966.xml,Chronic,COMPARISON: None. INDICATION: XXXX. FINDINGS: The heart size and pulmonary vascularity appear within normal limits. The lungs are free of focal airspace disease. No pleural effusion or pneumothorax is seen. Scoliosis and degenerative changes are present in the spine. IMPRESSION: 1. No evidence of active disease.,['spine/degenerative'],,./data/openi/xrays/CXR2966_IM-1359-1001.png
```

spacy 2.3.3
```
(Pdb) p [sent.text for sent in doc.sentences]
['0', 'b373d4199a2e1d24574cf307edd4687fd2a0cd7a7e1e94f7c2ff0419803be8d6', '1', "['spine/degenerative', 'scoliosis']", '2', '/lfs/raiders2/0/jdunnmon/repos/metal-experiments/data/openi/raw_reports/2966.xml', 'Chronic', 'COMPARISON:', 'None.', 'INDICATION:', 'XXXX.', 'FINDINGS:', 'The heart size and pulmonary vascularity appear within normal limits.', 'The lungs are free of focal airspace disease.', 'No pleural effusion or pneumothorax is seen.', 'Scoliosis and degenerative changes are present in the spine.', 'IMPRESSION:', '1.', 'No evidence of active disease.', "['spine/degenerative']", './data/openi/xrays/CXR2966_IM-1359-1001.png']
```

spacy 2.3.2
```
p [sent.text for sent in doc.sentences]
['0', 'b373d4199a2e1d24574cf307edd4687fd2a0cd7a7e1e94f7c2ff0419803be8d6', '1', "['spine/degenerative', 'scoliosis']", '2', '/lfs/raiders2/0/jdunnmon/repos/metal-experiments/data/openi/raw_reports/2966.xml', 'Chronic', 'COMPARISON: None.', 'INDICATION: XXXX.', 'FINDINGS: The heart size and pulmonary vascularity appear within normal limits.', 'The lungs are free of focal airspace disease.', 'No pleural effusion or pneumothorax is seen.', 'Scoliosis and degenerative changes are present in the spine.', 'IMPRESSION: 1.', 'No evidence of active disease.', "['spine/degenerative']", './data/openi/xrays/CXR2966_IM-1359-1001.png']
```

**Comment by HiromuHota** [comment]
https://github.com/explosion/spaCy/pull/5910 adds `:` as one of the default punctuators.

**Comment by HiromuHota** [comment]
https://spacy.io/usage/v2-2
> The default punctuation in the Sentencizer has been extended and now includes more characters common in various languages. This also means that the results it produces may change, depending on your text. If you want the previous behavior with limited characters, set punct_chars=[".", "!", "?"] on initialization.

**Review by SenWu — APPROVED** [review]
LGTM

**Pull request merged**
