### PR TITLE
Update visual.py

### PR DESCRIPTION
**Pull request by annelhote**
Typo in documentation

### CODE REVIEW

**Comment by HiromuHota** [comment]
@annelhote Thanks for your contribution.
Unfortunately, the CI tests failed because goanpeca/setup-miniconda@v1 needs to be updated.
I'll update it later today.

**Comment by SenWu** [comment]
Hi @annelhote, can you pull the master branch?

Thanks,
Sen

**Comment by annelhote** [comment]
Hey @SenWu it seems to be OK

**Review by SenWu — APPROVED** [review]
LGTM

**Comment by SenWu** [comment]
Merged! Thanks!

**Pull request merged**
