### PR TITLE
Merge _apply_mt and _apply_st for maintainability

### PR DESCRIPTION
**Pull request by HiromuHota**
This PR becomes ready for review when a dependent PR #342 is merged.

### CODE REVIEW

**Comment by SenWu** [comment]
Why coverage decreased 13.9%?

**Comment by HiromuHota** [comment]
@SenWu Good catch! Let me rebase and see what would happen.

**Comment by HiromuHota** [comment]
The test on OSX failed with the following log messages:

```
tests/test_meta.py::test_meta_connection_strings PASSED                  [  2%]
tests/candidates/test_candidates.py::test_ngram_split PASSED             [  4%]
tests/candidates/test_candidates.py::test_span_char_start_and_char_end PASSED [  6%]
tests/candidates/test_candidates.py::test_cand_gen_cascading_delete PASSED [  8%]
tests/candidates/test_candidates.py::test_cand_gen PASSED                [ 10%]
tests/candidates/test_candidates.py::test_ngrams PASSED                  [ 12%]
tests/candidates/test_candidates.py::test_row_col_ngram_extraction PASSED [ 14%]
tests/candidates/test_candidates.py::test_mention_longest_match PASSED   [ 17%]
tests/candidates/test_candidates.py::test_multimodal_cand Fatal Python error: Segmentation fault
Current thread 0x000000010698c5c0 (most recent call first):
  File "/Users/travis/build/HiromuHota/fonduer/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126 in connect
  File "/Users/travis/build/HiromuHota/fonduer/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481 in connect
  File "/Users/travis/build/HiromuHota/fonduer/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114 in connect
  File "/Users/travis/build/HiromuHota/fonduer/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639 in __connect
...
```

The whole log messages are available at https://travis-ci.com/HiromuHota/fonduer/jobs/249238898.

I can't reproduce this issue on my local OSX.

**Comment by HiromuHota** [comment]
Seems like I'm hitting this issue: https://github.com/psycopg/psycopg2/issues/478.

**Comment by HiromuHota** [comment]
Close this PR for now as I feel this Segmentation fault error needs more investigation.

**Pull request closed without merging**
