### PR TITLE
Add multiline Japanese strings support to HocrVisualParser() to fix #534 and redo #537

### LINKED ISSUE #534: HOCRParser fails to multiline Japanese strings
## Description of the bug
HocrVisualParser() fails to multiline Japanese strings like "チェーン店\n本・支店".
Hocr parser result does not aligne with spacy parse result and throws an error 
`"RuntimeError: ('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")"`
This situation same as "hocr tokens: ['AAAA', 'BBBB']", "spacy tokens: ['AAA', 'AB', 'B', 'BB']".
This might because spacy recognizes parts of different line words as one word like 'AB'. 

## To Reproduce
1. Add test codes into "./tests/parser/test_parser.py"
~~~
def test_parse_hocr_with_multiline_ja():
    docs_path = "tests/data/hocr_simple/jtest.hocr"
    preprocessor = HOCRDocPreprocessor(docs_path, space=False)
    doc = next(iter(preprocessor))
    parser_udf = get_parser_udf(
        structural=True,
        tabular=True,
        lingual=True,
        language="ja",
        visual_parser=HocrVisualParser(),
    )
    doc = parser_udf.apply(doc)
    assert doc.name == "jtest"
~~~
2. Run 'pytest ./tests/parser/test_parser.py::test_parse_hocr_with_multiline_ja'

### jtest.hocr
~~~
<?xml version="1.0" ?>
  <html>
    <head>
      <meta content="Generated OCRed text" name="ocr-system"/>
      <meta content="ocr_page ocr_line ocrx_word" name="ocr-capabilities"/>
    </head>
    <body>
      <div class="ocr_page" id="page_1" title="bbox 0 0 595 842">
          <div class="ocr_line" id="line_1_1" title="bbox 70 156 73 157">
            <span class="ocrx_word" id="word_1_1" title="bbox 70 156 73 157">チェーン店</span>
          </div>
          <div class="ocr_line" id="line_1_2" title="bbox 83 171 89 172">
            <span class="ocrx_word" id="word_1_2" title="bbox 83 171 89 172">本・支店</span>
          </div>
      </div>
    </body>
  </html>
~~~

## Expected behavior
Get aligned tokens like "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店', '本', '・', '支店']"

## Error Logs/Screenshots
~~~
Document jtest not added to database, because of parse error: 
('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")
Traceback (most recent call last):
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/parser.py", line 246, in apply
    document.name, document.sentences
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/parser.py", line 244, in <listcomp>
    y
  File "/home/miyata/work/fonduer/git/fonduer/src/fonduer/parser/visual_parser/hocr_visual_parser.py", line 135, in parse
    f"spacy tokens: {spacy_tokens}",
RuntimeError: ('Tokens are not aligned!', "hocr tokens: ['チェーン店', '本・支店']", "spacy tokens: ['チェーン', '店本', '・', '支店']")
~~~

## Environment (please complete the following information)
 - OS: Ubuntu 18.04
 - PostgreSQL Version: 10.15
 - Poppler Utils Version: 0.62.0
 - Fonduer Version: 0.8.4+dev
 - Spacy Version: 2.3.1 

## Additional context
I have tried some English hocr examples, but I could not find same problems.

### PR DESCRIPTION
**Pull request by YasushiMiyata**
## Description of the problems or issues

**Is your pull request related to a problem? Please describe.**
See #534. 
This request redoes #537, which needs prior fixing #538 (fixed by #539). 

**Does your pull request fix any issue.**
See #534

## Description of the proposed changes
In case of multi line Japanese strings 'AAAA\nBBBB', spacy[ja] sometimes generates tokens ['AAA', 'AB', 'B', 'BB']. Proposal defines bbox of 'AB' as a multi line word (i.e. left is min left of ['A','B'], top is the top of 'A', right is max right of ['A','B'] and bottom is the bottom of 'B').

## Test plan
This is cause of Japanese morphological analysis. So, I have added Japanese test data to 'tests/data/hocr_simple/japan.hocr' and test code to 'tests/parser/test_parser.py::test_parse_hocr'

## Checklist

* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] I have updated the CHANGELOG.rst accordingly.

### CODE REVIEW

**Review by lukehsiao — APPROVED** [review]
It seems clear that the behavior is changed (e.g., that RuntimeError will no longer be raised). I don't know if there will be any issues for downstream applications with this change, but I'm inclined to trust your judgement, since you're probably the one who has used it more than average.

Can you manually rebase this on the master branch so there aren't any conflicts?

I'll let @SenWu chime in also.

**Comment by YasushiMiyata** [comment]
@lukehsiao Thank you for review. Do you mean "manually rebase" is rebasing branch to master in my local or remote repository, or in this upstream? About local or remote, I will check. About upstream, I have no write access.

**Comment by YasushiMiyata** [comment]
@lukehsiao I have rebase on my local master, but I could not get the reason of conflicts. All codes of rebase original and destination are the same but rebase command shows conflict messages. 
I have tried `git rebase --skip` after some commands of resolving conflicts like `git am --show-current-patch`, `git rebase --continue` and so on. It is maybe because there are some cached data remains...

**Comment by lukehsiao** [comment]
@YasushiMiyata I'll take a look, one sec.

**Comment by lukehsiao** [comment]
@YasushiMiyata I'm able to resolve the rebase after "skipping" two commits and resolving the conflicts on another two. I can't force push to your PR, though, so I don't think there is an easy way for me to manually rebase this PR. 

```
git checkout -b YasushiMiyata-master master
git pull https://github.com/YasushiMiyata/fonduer.git master
git rebase master
<resolve conflict with tests/test_postgres.py>
git add -u
git rebase --continue
git rebase --skip
<resolve conflict with test_parser>
git add -u
git rebase --continue
git rebase --skip
```

Those were the steps I took to get to a state rebased on `master`. Can you give that a try?

**Comment by YasushiMiyata** [comment]
@lukehsiao
I did rebase with `--continue` and `--skip` and got following results.
I think it would be better to start over this pull request with fork process. 
Would you reject this pull request if this process is inappropriate?

> $git rebase --continue
Applying: Fix incorrect assertion in test_parser.py
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

> git rebase --skip
Applying: Fix test_parser.py assertion depended on python version.
Using index info to reconstruct a base tree...
M       tests/parser/test_parser.py
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Change variable name 'd' to 'candidate'
Using index info to reconstruct a base tree...
M       tests/test_postgres.py
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Add multiline Japanese strings support to HocrVisualParser() to fix #534 and redo #537
Applying: Add CHANGELOG of #540

**Comment by YasushiMiyata** [comment]
@lukehsiao 
I have tried rebase once again, and complete with no force push (no `--skip` command).
Sorry to bother you, but would you mind re-checking to be able to merge? 
The rebase failer seems my mistaking of rebase target.

**Comment by lukehsiao** [comment]
@YasushiMiyata, maybe you could add me as a collaborator on your repo, and let me force push so I can fix the rebase?

**Comment by lukehsiao** [comment]
I pushed a master-rebased version to:

https://github.com/YasushiMiyata/fonduer/commits/YasushiMiyata-master. 

Does that help?

**Comment by YasushiMiyata** [comment]
@lukehsiao, I add you to my repository as a collaborator.

Thank you for the explanation with video. 
In the last view, there are same logs but different ID like followings:
```
28e4d94 - (HEAD -> YasushiMiyata-master) Fix incorrect assertion in test_parser.py
ce9f946 - Fix test code test_postgres.py::test_cand_gen_cascading_delete (Fix #538)
```
```
4e7af04 - Fix test code test_postgres.py::test_cand_gen_cascading_delete (Fix #538)
41f34f1 - Fix incorrect assertion in test_parser.py
```
Maybe, it's cause of this error. I think that original cause is possibly my merge or rebase in the wrong oder.

**Comment by YasushiMiyata** [comment]
Thank you! I check it.

**Comment by YasushiMiyata** [comment]
@lukehsiao, I have tried rebasing and got following result without errors.
Is it okey? Can't i do anything?
```
(fonduer) (base) miyata@miyata-VB:~/work/fonduer/git/0426/fonduer$ git pull --rebase
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/YasushiMiyata/fonduer
 * [new branch]      YasushiMiyata-master -> origin/YasushiMiyata-master
Already up to date.
Current branch master is up to date.
(fonduer) (base) miyata@miyata-VB:~/work/fonduer/git/0426/fonduer$ git push
Everything up-to-date
```

**Comment by YasushiMiyata** [comment]
I also think it's better way to start over this PR. I close this PR. Thanks a lot!

**Pull request closed without merging**
