### PR TITLE
Use unidic instead of ipadic for Japanese (#231)

### PR DESCRIPTION
**Pull request by HiromuHota**

### CODE REVIEW

**Comment by HiromuHota** [comment]
This is actually a bug fix rather than enhancement.

**Comment by SenWu** [comment]
It failed on Mac tests, can you double check there? Thanks! @HiromuHota

**Comment by HiromuHota** [comment]
I'll insert a sanity-check about mecab configuration to `.travis.yml`. Please bear with me for a while.

**Comment by HiromuHota** [comment]
On mac, the sanity check command: `mecab -D` returns `param.cpp(69) [ifs] no such file or directory: /usr/local/lib/mecab/dic/ipadic/dicrc`

**Pull request merged**
