### PR TITLE
Upload to coveralls.io only if 'push' on 'HazyResearch/fonduer'

### LINKED ISSUE #391: GitHub Actions fail on forked repository
**Describe the bug**

GitHub Actions fail on a forked repository because "Upload to coveralls.io" step fails.

**To Reproduce**
1. Fork HazyResearch/fonduer
2. Push any commit to your forked repository
3. GitHub Actions fails

**Expected behavior**

"Upload to coveralls.io" runs only on HazyResearch/fonduer

**Error Logs/Screenshots**

image

### PR DESCRIPTION
**Pull request by HiromuHota**
This will close #391 .

### CODE REVIEW

**Comment by HiromuHota** [comment]
Please see the step is skipped on a forked repository.
https://github.com/HiromuHota/fonduer/actions/runs/75405791.

**Comment by HiromuHota** [comment]
This PR fails.
https://github.com/HazyResearch/fonduer/actions/runs/75436780

> coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.

- The "Upload to coveralls.io" step runs because this PR is against 'HazyResearch/fonduer'
- But, this PR fails because a token for coveralls is not available.

@lukehsiao any idea?

**Comment by lukehsiao** [comment]
Not sure. The configuration sets the env var, and the secret is in the repo:

image

This might be due to the secret not being passed correctly?

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by HiromuHota** [comment]
Yes, it is clearly mentioned in https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow that 
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

**Comment by HiromuHota** [comment]
Or maybe "Coveralls GitHub Action" works better.
https://github.com/marketplace/actions/coveralls-github-action

**Comment by HiromuHota** [comment]
"Coveralls GitHub Action" only supports LCOV file (`lcov.info`), while coverage.py, used by Fonduer, generates `.coverage`.
https://github.com/coverallsapp/github-action/issues/30

**Comment by lukehsiao** [comment]
Hmmm, I'm fine with switching to codecov, there is no particular reason we are using coveralls.

**Comment by SenWu** [comment]
I think codecov is easier solution here.

**Comment by HiromuHota** [comment]
Let's fix this now. We can discuss if we should switch to codecov in a different issue/pr.

**Comment by AndreMiras** [comment]
Before doing the switch give that one a try, I've just built a coveralls action that works for pull requests https://github.com/marketplace/actions/coveralls-python

**Pull request merged**
