### PR TITLE
Incorporate entity_confusion_matrix as a first-class citizen

### PR DESCRIPTION
**Pull request by HiromuHota**
This PR will become ready for review once I submit a corresponding PR for tutorials.

### CODE REVIEW

**Comment by HiromuHota** [comment]
Snorkel-metal has an API for a confusion matrix with different input/output.
https://github.com/HazyResearch/metal/blob/c24e3772e25ac6d0917b8b7af4c1bcb92928f84a/metal/analysis.py#L217-L242

To avoid confusion, Fonduer should use the Metal's API if Metal has one.
@SenWu Thoughts?

**Comment by HiromuHota** [comment]
Snokel also has a slightly different API.
https://github.com/HazyResearch/snorkel/blob/1d16ae6a6dba0f51c60d5a4179576d2d89134160/snorkel/learning/classifier.py#L93-L122

**Comment by SenWu** [comment]
> Snorkel-metal has an API for a confusion matrix with different input/output.
> https://github.com/HazyResearch/metal/blob/c24e3772e25ac6d0917b8b7af4c1bcb92928f84a/metal/analysis.py#L217-L242
> 
> To avoid confusion, Fonduer should use the Metal's API if Metal has one.
> @SenWu Thoughts?

I would suggest to have Fonduer own implementation because of the different needs from Fonduer user.

**Comment by HiromuHota** [comment]
Thanks for you suggestion!
I believe Snorkel's implementation is more similar to Fonduer's because Snorkel's returns a tuple of TP, FP, TN, FN.

**Pull request merged**
